/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/ECO.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.48, 0, 0.48]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1L0021__Convertido__ARD-geom"].geometry}
          material={materials._1L0021__Convertido__ARD_front}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1L0021__Convertido__ARD-geom_1"].geometry}
          material={materials["back-dil"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["_1L0021__Convertido__ARD-geom_2"].geometry}
          material={materials._1L0021__Convertido__ARD_edge}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ECO.gltf");
